export const SHOW_CURRENT_USER_SUCCESS = 'app/users/SHOW_CURRENT_USER_SUCCESS';

export const GET_USER_LIST_REQUEST = 'app/users/GET_USER_LIST_REQUEST'
export const GET_USER_LIST_ERROR = 'app/users/GET_USER_LIST_ERROR'
export const GET_USER_LIST_SUCCESS = 'app/users/GET_USER_LIST_SUCCESS'


export const GET_SELECTED_USER_REQUEST = 'app/users/GET_SELECTED_USER_REQUEST'
export const GET_SELECTED_USER_ERROR = 'app/users/GET_SELECTED_USER_ERROR'
export const GET_SELECTED_USER_SUCCESS = 'app/users/GET_SELECTED_USER_SUCCESS'

export const CHANGE_USER_IMAGE_REQUEST = 'app/users/CHANGE_USER_IMAGE_REQUEST'
export const CHANGE_USER_IMAGE_ERROR = 'app/users/CHANGE_USER_IMAGE_ERROR'
export const CHANGE_USER_IMAGE_SUCCESS = 'app/users/CHANGE_USER_IMAGE_SUCCESS'


export const CHANGE_USER_INFORMATION_REQUEST = 'app/users/CHANGE_USER_INFORMATION_REQUEST'
export const CHANGE_USER_INFORMATION_ERROR = 'app/users/CHANGE_USER_INFORMATION_ERROR'
export const CHANGE_USER_INFORMATION_SUCCESS = 'app/users/CHANGE_USER_INFORMATION_SUCCESS'




