export const ADD_POST_REQUEST = 'app/posts/ADD_POST_REQUEST';
export const ADD_POST_SUCCESS = 'app/posts/ADD_POST_SUCCESS';
export const ADD_POST_ERROR = 'app/posts/ADD_POST_ERROR';

export const GET_POSTS_REQUEST = 'app/posts/GET_POSTS_REQUEST';
export const GET_POSTS_ERROR = 'app/posts/GET_POSTS_ERROR';
export const GET_POSTS_SUCCESS = 'app/posts/GET_POSTS/SUCCESS';


export const GET_SELECTED_POST_REQUEST = 'app/posts/GET_SELECTED_POST_REQUEST'
export const GET_SELECTED_POST_ERROR = 'app/posts/GET_SELECTED_POST_ERROR'
export const GET_SELECTED_POST_SUCCESS = 'app/posts/GET_SELECTED_POST_SUCCESS'


export const GET_SELECTED_USER_POST_LIST_REQUEST = 'app/posts/GET_SELECTED_USER_POST_LIST_REQUEST'
export const GET_SELECTED_USER_POST_LIST_ERROR = 'app/posts/GET_SELECTED_USER_POST_LIST_ERROR'
export const GET_SELECTED_USER_POST_LIST_SUCCESS = 'app/posts/GET_SELECTED_USER_POST_LIST_SUCCESS'